LOAD DATA INFILE 'Location.csv'
INTO TABLE location
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES ;

LOAD DATA  INFILE 'AQ cleaned.csv'
IGNORE
INTO TABLE airpollution
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES ;

LOAD DATA  INFILE 'Weather cleaned.csv'
IGNORE
INTO TABLE weather
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES ;

LOAD DATA  INFILE 'Detectors.csv'
IGNORE
INTO TABLE detectors
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES ;

LOAD DATA  INFILE 'LinksCleaned.csv'
IGNORE
INTO TABLE links
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES ;

LOAD DATA  INFILE 'utdcleaned.csv'
IGNORE
INTO TABLE UTD
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES ;

LOAD DATA  INFILE 'MVIcleaned.csv'
IGNORE
INTO TABLE mvi
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES ;